# Generated by Django 5.2.10 on 2026-03-01 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_account', to='authors.author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
