# Generated by Django 4.2.11 on 2026-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authoraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_local',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
