# Generated by Django 5.2.11 on 2026-03-01 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_authoraccount'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(blank=True, help_text='Fully qualified ID URL for this comment.', max_length=500, null=True, unique=True)),
                ('comment', models.TextField()),
                ('content_type', models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=64)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='authors.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='entries.entry')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='EntryLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(blank=True, help_text='Fully qualified ID URL for this like.', max_length=500, null=True, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_likes', to='authors.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='entries.entry')),
            ],
            options={
                'ordering': ['-published'],
                'constraints': [models.UniqueConstraint(fields=('author', 'entry'), name='unique_author_entry_like')],
            },
        ),
    ]
