# Generated by Django 5.2.11 on 2026-03-15 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authoraccount'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(blank=True, help_text='Fully qualified ID URL for this comment like.', max_length=500, null=True, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='authors.author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interactions.comment')),
            ],
            options={
                'ordering': ['-published'],
                'constraints': [models.UniqueConstraint(fields=('author', 'comment'), name='unique_author_comment_like')],
            },
        ),
    ]
