# Generated by Django 4.2.11 on 2026-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelationship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
