# Generated by Django 5.2.11 on 2026-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelationship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=16),
        ),
    ]
