# Generated by Django 5.2.11 on 2026-02-27 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(blank=True, help_text='Fully qualified URL ID of the entry on this node.', max_length=500, null=True, unique=True)),
                ('web', models.URLField(blank=True, help_text='HTML URL for viewing this entry.', max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=64)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authors.author')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
