# Generated by Django 5.2.11 on 2026-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_remove_entry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='external_id',
            field=models.CharField(blank=True, help_text='External ID for deduplication (e.g. GitHub event ID).', max_length=255, null=True, unique=True),
        ),
    ]
