# Generated by Django 5.2.11 on 2026-03-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_remove_entry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedimage',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_images', to='entries.entry'),
        ),
        migrations.AddField(
            model_name='hostedimage',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=16),
        ),
    ]
