# Generated by Django 5.2.11 on 2026-03-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_entry_external_id'),
        ('entries', '0006_hostedimage_entry_hostedimage_visibility'),
    ]

    operations = [
    ]
