# Generated by Django 5.2.11 on 2026-03-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_merge_20260316_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image_urls',
        ),
    ]
