# Generated by Django 5.2.11 on 2026-03-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_merge_20260315_2349'),
        ('entries', '0008_remove_entry_image_urls'),
    ]

    operations = [
    ]
