# Generated by Django 4.2.11 on 2026-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_merge_20260322_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], db_index=True, default='PUBLIC', max_length=16),
        ),
    ]
