# Generated by Django 5.2.11 on 2026-03-23
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0009_merge_20260322_2021"),
        ("authors", "0002_authoraccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryFederationTarget",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        primary_key=True, default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sent_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federation_targets",
                        to="entries.entry",
                    ),
                ),
                (
                    "recipient_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_federation_targets",
                        to="authors.author",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry", "recipient_author"),
                        name="unique_entry_federation_target",
                    )
                ]
            },
        ),
    ]

