# Generated by Django 5.2.11 on 2026-03-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_entry_federation_targets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryFederationTarget',
        ),
    ]
