# Generated by Django 5.2.11 on 2026-03-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_delete_entryfederationtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'CommonMark')], default='text/plain', max_length=64),
        ),
    ]
