# Generated by Django 4.2.11 on 2026-03-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_add_database_indexes'),
        ('entries', '0011_delete_entryfederationtarget'),
    ]

    operations = [
    ]
