# Generated by Django 5.2.11 on 2026-03-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_remove_image_content_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='external_image_urls',
            field=models.TextField(blank=True, default='', help_text='Newline-separated external image URLs to display with this entry.'),
        ),
    ]
