# Generated by Django 5.2.11 on 2026-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_add_external_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='external_image_urls',
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'CommonMark'), ('image', 'Image')], default='text/plain', max_length=64),
        ),
    ]
