# Generated by Django 5.2.11 on 2026-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_restore_image_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A brief description of the entry.'),
        ),
    ]
