# Generated by Django 5.2.11 on 2026-03-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_alter_entry_content_type'),
        ('entries', '0012_merge_20260329_1354'),
        ('entries', '0015_add_entry_description'),
    ]

    operations = [
    ]
