# Generated by Django 5.2.11 on 2026-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_merge_20260329_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(),
        ),
    ]
