# Generated by Django 5.2.11 on 2026-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_alter_entry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'CommonMark'), ('image/png;base64', 'PNG (base64)'), ('image/jpeg;base64', 'JPEG (base64)'), ('image/gif;base64', 'GIF (base64)'), ('image/webp;base64', 'WebP (base64)'), ('application/base64', 'Image (base64; unknown type)'), ('image', 'Image (legacy)')], default='text/plain', max_length=64),
        ),
    ]
