# Generated by Django 5.2.11 on 2026-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_alter_entry_content_alter_entry_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'CommonMark'), ('Image', 'Image')], default='text/plain', max_length=64),
        ),
    ]
