# Generated by Django 5.2.11 on 2026-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_alter_entry_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedimage',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hostedimage',
            name='data_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
