# Generated by Django 5.2.11 on 2026-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_hostedimage_db_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.CharField(default='2026-04-01T13:12:16.146251+00:00', editable=False),
        ),
    ]
