# Generated by Django 5.2.11 on 2026-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_alter_entry_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
