# Generated by Django 5.2.11 on 2026-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0023_alter_entry_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.DateTimeField(db_index=True, default='2026-04-01T18:46:57.920229+00:00'),
        ),
    ]
