# Generated by Django 5.2.11 on 2026-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0024_alter_entry_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.DateTimeField(db_index=True, default='2026-04-01T20:02:24.936747+00:00'),
        ),
    ]
