from django.urls import path

from interactions import views as interactions_views

from . import views

app_name = "entries"

urlpatterns = [
    path(
        "stream/",
        views.stream_page,
        name="stream-page",
    ),
    path(
        "entries/new/",
        views.entry_create_me_page,
        name="entry-create-me",
    ),
    path(
        "authors/<uuid:author_id>/entries/",
        views.author_entries_page,
        name="author-entries",
    ),
    path(
        "authors/<uuid:author_id>/entries/new/",
        views.entry_create_page,
        name="entry-create",
    ),
    path(
        "authors/<uuid:author_id>/images/upload/",
        views.image_upload_page,
        name="image-upload",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/",
        views.entry_detail_page,
        name="entry-detail",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/comment/",
        views.entry_comment_create_page,
        name="entry-comment-create",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/like/",
        views.entry_like_page,
        name="entry-like",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/unlike/",
        views.entry_unlike_page,
        name="entry-unlike",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/<uuid:comment_id>/like/",
        views.comment_like_page,
        name="comment-like",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/<uuid:comment_id>/unlike/",
        views.comment_unlike_page,
        name="comment-unlike",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/<uuid:comment_id>/delete/",
        views.comment_delete_page,
        name="comment-delete",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/edit/",
        views.entry_edit_page,
        name="entry-edit",
    ),
    path(
        "authors/<uuid:author_id>/entries/<uuid:entry_id>/delete/",
        views.entry_delete_page,
        name="entry-delete",
    ),
    path(
        "api/stream",
        views.stream_api,
        name="stream-api",
    ),
    path(
        "api/stream/",
        views.stream_api,
    ),
    path(
        "api/media/images/<uuid:image_id>/",
        views.serve_hosted_image,
        name="serve-hosted-image",
    ),
    path(
        "api/authors/<uuid:author_id>/images",
        views.image_upload_api,
        name="image-upload-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries",
        views.author_entries_api,
        name="author-entries-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/image",
        views.entry_image_api_by_entry_id,
        name="entry-image-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>",
        views.entry_detail_api,
        name="entry-detail-api",
    ),
    path(
        "api/entries/<path:entry_fqid>/image",
        views.entry_image_api_by_fqid,
        name="entry-image-fqid-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/comments",
        interactions_views.entry_comments_api,
        name="entry-comments-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/",
        interactions_views.entry_comments_api,
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/<uuid:comment_id>/likes",
        interactions_views.comment_likes_api,
        name="comment-likes-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/<uuid:comment_id>/likes/",
        interactions_views.comment_likes_api,
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/comments/<path:comment_ref>",
        interactions_views.entry_comment_detail_api,
        name="entry-comment-detail-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/likes",
        interactions_views.entry_likes_api,
        name="entry-likes-api",
    ),
    path(
        "api/authors/<uuid:author_id>/entries/<uuid:entry_id>/likes/",
        interactions_views.entry_likes_api,
    ),

    # --- Commented API (serial-based) ---
    path(
        "api/authors/<uuid:author_id>/commented",
        interactions_views.author_commented_api,
        name="author-commented-api",
    ),
    path(
        "api/authors/<uuid:author_id>/commented/",
        interactions_views.author_commented_api,
    ),
    path(
        "api/authors/<uuid:author_id>/commented/<uuid:comment_id>/likes",
        interactions_views.commented_likes_api,
        name="commented-likes-api",
    ),
    path(
        "api/authors/<uuid:author_id>/commented/<uuid:comment_id>/likes/",
        interactions_views.commented_likes_api,
    ),
    path(
        "api/authors/<uuid:author_id>/commented/<uuid:comment_id>",
        interactions_views.author_commented_detail_api,
        name="author-commented-detail-api",
    ),
    path(
        "api/authors/<uuid:author_id>/commented/<uuid:comment_id>/",
        interactions_views.author_commented_detail_api,
    ),

    # --- Liked API (serial-based) ---
    path(
        "api/authors/<uuid:author_id>/liked",
        interactions_views.author_liked_api,
        name="author-liked-api",
    ),
    path(
        "api/authors/<uuid:author_id>/liked/",
        interactions_views.author_liked_api,
    ),
    path(
        "api/authors/<uuid:author_id>/liked/<uuid:like_id>",
        interactions_views.author_liked_detail_api,
        name="author-liked-detail-api",
    ),
    path(
        "api/authors/<uuid:author_id>/liked/<uuid:like_id>/",
        interactions_views.author_liked_detail_api,
    ),

    # --- FQID shortcut routes ---
    path(
        "api/entries/<path:entry_fqid>/comments",
        interactions_views.entry_fqid_comments_api,
        name="entry-fqid-comments-api",
    ),
    path(
        "api/entries/<path:entry_fqid>/likes",
        interactions_views.entry_fqid_likes_api,
        name="entry-fqid-likes-api",
    ),
    path(
        "api/commented/<path:comment_fqid>",
        interactions_views.commented_fqid_api,
        name="commented-fqid-api",
    ),
    path(
        "api/liked/<path:like_fqid>",
        interactions_views.liked_fqid_api,
        name="liked-fqid-api",
    ),
]

