# Generated by Django 5.2.11 on 2026-03-21 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('base_url', models.URLField(help_text="The remote node's base URL (e.g. https://othernode.herokuapp.com)", unique=True)),
                ('outgoing_username', models.CharField(max_length=200)),
                ('outgoing_password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to block this node without deleting the record.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('node_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_node', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
